// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TccSharkTank.Infrastructure.Persistence;

#nullable disable

namespace TccSharkTank.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528150519_AddPerfilHistoriaAndIdeiaBusinessFields")]
    partial class AddPerfilHistoriaAndIdeiaBusinessFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("TccSharkTank.Domain.Entities.ChtConversa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_conversa_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cht_conversa_create_date");

                    b.Property<long?>("IdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_conversa_ideia_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cht_conversa_update_date");

                    b.Property<long>("Usuario1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_conversa_usuario1_id");

                    b.Property<long>("Usuario2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_conversa_usuario2_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeiaId");

                    b.HasIndex("Usuario1Id");

                    b.HasIndex("Usuario2Id");

                    b.ToTable("cht_conversa", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.ChtMensagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_mensagem_id");

                    b.Property<long>("ConversaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_mensagem_conversa_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cht_mensagem_create_date");

                    b.Property<bool>("Lida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_mensagem_lida");

                    b.Property<long>("RemetenteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cht_mensagem_remetente_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("cht_mensagem_texto");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cht_mensagem_update_date");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("cht_mensagem", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.GovDenuncia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("gov_denuncia_id");

                    b.Property<long>("AlvoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gov_denuncia_alvo_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("gov_denuncia_create_date");

                    b.Property<long>("DenuncianteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("denunciante_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("gov_denuncia_motivo");

                    b.Property<string>("ObservacaoAdm")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("gov_denuncia_obs_adm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("gov_denuncia_status");

                    b.Property<string>("TipoAlvo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("gov_denuncia_tipo_alvo");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("gov_denuncia_update_date");

                    b.HasKey("Id");

                    b.HasIndex("DenuncianteId");

                    b.ToTable("gov_denuncia", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_categoria_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_categoria_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ida_categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "tecnologia"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Agro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "inovacao"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "infraestrutura"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "moda"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "automobilismo"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "sustentabilidade"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Comodidade"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "lazer"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "uso diario"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Moradia"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Energia"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "maritimo"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "aeronáutico"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "outros"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaComentario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_comentario_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_comentario_create_date");

                    b.Property<long>("IdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_comentario_ideia_id");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_comentario_parent_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_comentario_texto");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_comentario_update_date");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_comentario_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeiaId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ida_comentario", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_documento_id");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_documento_arquivo");

                    b.Property<long>("IdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_ideia_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeiaId");

                    b.ToTable("ida_documento", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaEstagio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_estagio_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_estagio_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ida_estagio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ideação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "MVP"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Tração"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Scale-up"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaIdeia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_id");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_categoria_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_create_date");

                    b.Property<int>("EstagioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("ida_estagio_id");

                    b.Property<string>("MotivoStatus")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_motivo_status");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_nome");

                    b.Property<string>("Regiao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_regiao");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_status_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_update_date");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_ida_ideia_ida_categoria_id");

                    b.HasIndex("EstagioId")
                        .HasDatabaseName("ix_ida_ideia_ida_estagio_id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ida_ideia", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_info_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_cnpj");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_create_date");

                    b.Property<decimal?>("CustosMensais")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_custos_mensais");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_descricao");

                    b.Property<decimal>("Fatia")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_fatia");

                    b.Property<decimal?>("Faturamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_faturamento");

                    b.Property<string>("FeedbackClientes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_feedback_clientes");

                    b.Property<long>("IdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_ideia_id");

                    b.Property<string>("Imagem")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_imagem");

                    b.Property<string>("LinkVideo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_link_video");

                    b.Property<int?>("QuantidadeClientes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_info_quantidade_clientes");

                    b.Property<int?>("TempoMercadoMeses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_info_tempo_mercado_meses");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_update_date");

                    b.Property<decimal>("ValorCaptacao")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("ida_info_valor_captacao");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("IdeiaId")
                        .IsUnique();

                    b.ToTable("ida_info", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_status_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_status_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ida_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "pendente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "aprovada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "reprovada"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfNotificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ntf_create_date");

                    b.Property<bool>("Lida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ntf_mensagem");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_tipo_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ntf_notificacao", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_tipo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ntf_tipo_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ntf_tipo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "prp aceita"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "prp recusada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "alerta"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "n"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "prp recebida"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "prp contraproposta"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PgtPagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pgt_pagamento_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgt_pagamento_create_date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("pgt_pagamento_descricao");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("pgt_pagamento_metodo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("pgt_pagamento_status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgt_pagamento_update_date");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("pgt_pagamento_valor");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pgt_pagamento", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpAceite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_aceite_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_aceite_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("prp_aceite", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "aceita"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "recusada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "pendente"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "contraproposta"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_info_id");

                    b.Property<int>("AceiteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_aceite_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_create_date");

                    b.Property<decimal>("FatiaPret")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_fatia_pret");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_mensagem");

                    b.Property<long>("PropostaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_proposta_id");

                    b.Property<string>("Retorno")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_retorno");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_update_date");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_valor");

                    b.HasKey("Id");

                    b.HasIndex("AceiteId");

                    b.HasIndex("PropostaId");

                    b.ToTable("prp_info", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpProposta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_create_date");

                    b.Property<long>("IdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_ideia_id");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_update_date");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("prp_proposta", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_create_date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_descricao");

                    b.Property<long?>("IdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_ideia_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_proposta_id");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_tipo_id");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeiaId");

                    b.HasIndex("PropostaId");

                    b.HasIndex("TipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("trn_log", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_tipo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_tipo_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("trn_tipo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "cadastro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "edição"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "proposta"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "login"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_cargo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_cargo_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("usu_cargo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "adm"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "empreendedor"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "investidor"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuPerfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_perfil_id");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_cep");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_create_date");

                    b.Property<DateTime?>("DataNasc")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_data_nasc");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_descricao");

                    b.Property<string>("Historia")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_historia");

                    b.Property<string>("InvestInteresses")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_invest_interesses");

                    b.Property<decimal?>("InvestTicketMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_invest_ticket_max");

                    b.Property<decimal?>("InvestTicketMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_invest_ticket_min");

                    b.Property<string>("LinkRedes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_link_redes");

                    b.Property<bool>("ReceberEmailAlertas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("usu_perfil_email_alertas");

                    b.Property<bool>("ReceberEmailMensagens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("usu_perfil_email_mensagens");

                    b.Property<bool>("ReceberEmailPropostas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("usu_perfil_email_propostas");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_update_date");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("usu_perfil", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuPlano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_plano_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_plano_nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("usu_plano", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "basico"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "pro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "elite"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_id");

                    b.Property<int>("CargoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_cargo_id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_nome");

                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("usu_plano_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_senha");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_sobrenome");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_telefone");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usu_usuario_usu_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usu_usuario_usu_email");

                    b.HasIndex("PlanoId");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("usu_usuario", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.ChtConversa", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany()
                        .HasForeignKey("IdeiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario1")
                        .WithMany()
                        .HasForeignKey("Usuario1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("Usuario2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ideia");

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.ChtMensagem", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.ChtConversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversa");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.GovDenuncia", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Denunciante")
                        .WithMany()
                        .HasForeignKey("DenuncianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Denunciante");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaComentario", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.IdaComentario", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ideia");

                    b.Navigation("Parent");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaDocumento", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany("Documentos")
                        .HasForeignKey("IdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ideia");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaIdeia", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaCategoria", "Categoria")
                        .WithMany("Ideias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.IdaEstagio", "Estagio")
                        .WithMany("Ideias")
                        .HasForeignKey("EstagioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.IdaStatus", "Status")
                        .WithMany("Ideias")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("Ideias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estagio");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaInfo", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithOne("Info")
                        .HasForeignKey("TccSharkTank.Domain.Entities.IdaInfo", "IdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ideia");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfNotificacao", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.NtfTipo", "Tipo")
                        .WithMany("Notificacoes")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("NotificacoesRecebidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PgtPagamento", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpInfo", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.PrpAceite", "Aceite")
                        .WithMany("Infos")
                        .HasForeignKey("AceiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.PrpProposta", "Proposta")
                        .WithMany("Infos")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aceite");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpProposta", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany("Propostas")
                        .HasForeignKey("IdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("Propostas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ideia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnLog", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany()
                        .HasForeignKey("IdeiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TccSharkTank.Domain.Entities.PrpProposta", "Proposta")
                        .WithMany()
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TccSharkTank.Domain.Entities.TrnTipo", "Tipo")
                        .WithMany("Logs")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ideia");

                    b.Navigation("Proposta");

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuPerfil", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("TccSharkTank.Domain.Entities.UsuPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuUsuario", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.UsuCargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuPlano", "Plano")
                        .WithMany("Usuarios")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.ChtConversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaCategoria", b =>
                {
                    b.Navigation("Ideias");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaComentario", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaEstagio", b =>
                {
                    b.Navigation("Ideias");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaIdeia", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Documentos");

                    b.Navigation("Info");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaStatus", b =>
                {
                    b.Navigation("Ideias");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfTipo", b =>
                {
                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpAceite", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpProposta", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnTipo", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuCargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuPlano", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuUsuario", b =>
                {
                    b.Navigation("Ideias");

                    b.Navigation("Logs");

                    b.Navigation("NotificacoesRecebidas");

                    b.Navigation("Perfil");

                    b.Navigation("Propostas");
                });
#pragma warning restore 612, 618
        }
    }
}
