// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TccSharkTank.Infrastructure.Persistence;

#nullable disable

namespace TccSharkTank.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaCategoria", b =>
                {
                    b.Property<int>("IdaCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_categoria_id");

                    b.Property<string>("IdaCategoriaNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_categoria_nome");

                    b.HasKey("IdaCategoriaId");

                    b.HasIndex("IdaCategoriaNome")
                        .IsUnique();

                    b.ToTable("ida_categoria", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaDocumento", b =>
                {
                    b.Property<long>("IdaDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_documento_id");

                    b.Property<string>("IdaDocumentoArquivo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_documento_arquivo");

                    b.Property<long>("IdaIdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_ideia_id");

                    b.HasKey("IdaDocumentoId");

                    b.HasIndex("IdaIdeiaId");

                    b.ToTable("ida_documento", null, t =>
                        {
                            t.HasCheckConstraint("ck_ida_documento_pdf", "ida_documento_arquivo LIKE '%.pdf'");
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaIdeia", b =>
                {
                    b.Property<long>("IdaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_id");

                    b.Property<int>("IdaCategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_categoria_id");

                    b.Property<string>("IdaMotivoStatus")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_motivo_status");

                    b.Property<string>("IdaNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_nome");

                    b.Property<int>("IdaStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_status_id");

                    b.Property<long>("IdaUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_usuario_id");

                    b.HasKey("IdaId");

                    b.HasIndex("IdaCategoriaId")
                        .HasDatabaseName("ix_ida_ideia_ida_categoria_id");

                    b.HasIndex("IdaNome")
                        .IsUnique();

                    b.HasIndex("IdaStatusId");

                    b.HasIndex("IdaUsuarioId");

                    b.ToTable("ida_ideia", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_info_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_create_date");

                    b.Property<long>("IdaIdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_ideia_id");

                    b.Property<string>("IdaInfoCnpj")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_cnpj");

                    b.Property<string>("IdaInfoDescricao")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_descricao");

                    b.Property<decimal>("IdaInfoFatia")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_fatia");

                    b.Property<string>("IdaInfoImagem")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_imagem");

                    b.Property<string>("IdaInfoLinkVideo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_link_video");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_info_update_date");

                    b.HasKey("Id");

                    b.HasIndex("IdaIdeiaId")
                        .IsUnique();

                    b.HasIndex("IdaInfoCnpj")
                        .IsUnique();

                    b.ToTable("ida_info", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaStatus", b =>
                {
                    b.Property<int>("IdaStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ida_status_id");

                    b.Property<string>("IdaStatusNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ida_status_nome");

                    b.HasKey("IdaStatusId");

                    b.HasIndex("IdaStatusNome")
                        .IsUnique();

                    b.ToTable("ida_status", (string)null);

                    b.HasData(
                        new
                        {
                            IdaStatusId = 1,
                            IdaStatusNome = "pendente"
                        },
                        new
                        {
                            IdaStatusId = 2,
                            IdaStatusNome = "aprovada"
                        },
                        new
                        {
                            IdaStatusId = 3,
                            IdaStatusNome = "reprovada"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfNotificacao", b =>
                {
                    b.Property<long>("NtfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_id");

                    b.Property<DateTime>("NtfCreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ntf_create_date");

                    b.Property<bool>("NtfLida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_lida");

                    b.Property<string>("NtfMensagem")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ntf_mensagem");

                    b.Property<int>("NtfTipoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_tipo_id");

                    b.Property<long>("NtfUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_usuario_id");

                    b.HasKey("NtfId");

                    b.HasIndex("NtfTipoId");

                    b.HasIndex("NtfUsuarioId");

                    b.ToTable("ntf_notificacao", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfTipo", b =>
                {
                    b.Property<int>("NtfTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ntf_tipo_id");

                    b.Property<string>("NtfTipoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ntf_tipo_nome");

                    b.HasKey("NtfTipoId");

                    b.HasIndex("NtfTipoNome")
                        .IsUnique();

                    b.ToTable("ntf_tipo", (string)null);

                    b.HasData(
                        new
                        {
                            NtfTipoId = 1,
                            NtfTipoNome = "prp aceita"
                        },
                        new
                        {
                            NtfTipoId = 2,
                            NtfTipoNome = "prp recusada"
                        },
                        new
                        {
                            NtfTipoId = 3,
                            NtfTipoNome = "alerta"
                        },
                        new
                        {
                            NtfTipoId = 4,
                            NtfTipoNome = "n"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpAceite", b =>
                {
                    b.Property<int>("PrpAceiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_aceite_id");

                    b.Property<string>("PrpAceiteNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_aceite_nome");

                    b.HasKey("PrpAceiteId");

                    b.HasIndex("PrpAceiteNome")
                        .IsUnique();

                    b.ToTable("prp_aceite", (string)null);

                    b.HasData(
                        new
                        {
                            PrpAceiteId = 1,
                            PrpAceiteNome = "aceita"
                        },
                        new
                        {
                            PrpAceiteId = 2,
                            PrpAceiteNome = "recusada"
                        },
                        new
                        {
                            PrpAceiteId = 3,
                            PrpAceiteNome = "pendente"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_info_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_create_date");

                    b.Property<int>("PrpAceiteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_aceite_id");

                    b.Property<decimal>("PrpInfoFatiaPret")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_fatia_pret");

                    b.Property<string>("PrpInfoMensagem")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_mensagem");

                    b.Property<string>("PrpInfoRetorno")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_retorno");

                    b.Property<decimal>("PrpInfoValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_valor");

                    b.Property<long>("PrpPropostaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_proposta_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prp_info_update_date");

                    b.HasKey("Id");

                    b.HasIndex("PrpAceiteId");

                    b.HasIndex("PrpPropostaId");

                    b.ToTable("prp_info", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpProposta", b =>
                {
                    b.Property<long>("PrpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_id");

                    b.Property<long>("PrpIdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_ideia_id");

                    b.Property<bool>("PrpStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_status");

                    b.Property<long>("PrpUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prp_usuario_id");

                    b.HasKey("PrpId");

                    b.HasIndex("PrpIdeiaId");

                    b.HasIndex("PrpUsuarioId");

                    b.ToTable("prp_proposta", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnLog", b =>
                {
                    b.Property<long>("TrnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_id");

                    b.Property<DateTime>("TrnCreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_create_date");

                    b.Property<string>("TrnDescricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_descricao");

                    b.Property<long?>("TrnIdeiaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_ideia_id");

                    b.Property<long?>("TrnPropostaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_proposta_id");

                    b.Property<int>("TrnTipoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_tipo_id");

                    b.Property<long?>("TrnUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_usuario_id");

                    b.HasKey("TrnId");

                    b.HasIndex("TrnIdeiaId");

                    b.HasIndex("TrnPropostaId");

                    b.HasIndex("TrnTipoId");

                    b.HasIndex("TrnUsuarioId");

                    b.ToTable("trn_log", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnTipo", b =>
                {
                    b.Property<int>("TrnTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("trn_tipo_id");

                    b.Property<string>("TrnTipoNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trn_tipo_nome");

                    b.HasKey("TrnTipoId");

                    b.HasIndex("TrnTipoNome")
                        .IsUnique();

                    b.ToTable("trn_tipo", (string)null);

                    b.HasData(
                        new
                        {
                            TrnTipoId = 1,
                            TrnTipoNome = "cadastro"
                        },
                        new
                        {
                            TrnTipoId = 2,
                            TrnTipoNome = "edição"
                        },
                        new
                        {
                            TrnTipoId = 3,
                            TrnTipoNome = "proposta"
                        },
                        new
                        {
                            TrnTipoId = 4,
                            TrnTipoNome = "login"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuCargo", b =>
                {
                    b.Property<int>("UsuCargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_cargo_id");

                    b.Property<string>("UsuCargoNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_cargo_nome");

                    b.HasKey("UsuCargoId");

                    b.HasIndex("UsuCargoNome")
                        .IsUnique();

                    b.ToTable("usu_cargo", (string)null);

                    b.HasData(
                        new
                        {
                            UsuCargoId = 1,
                            UsuCargoNome = "adm"
                        },
                        new
                        {
                            UsuCargoId = 2,
                            UsuCargoNome = "empreendedor"
                        },
                        new
                        {
                            UsuCargoId = 3,
                            UsuCargoNome = "investidor"
                        });
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuPerfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_perfil_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_create_date");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_update_date");

                    b.Property<string>("UsuPerfilCep")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_cep");

                    b.Property<DateTime?>("UsuPerfilDataNasc")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_data_nasc");

                    b.Property<string>("UsuPerfilDescricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_descricao");

                    b.Property<string>("UsuPerfilLinkRedes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_perfil_link_redes");

                    b.Property<long>("UsuUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuUsuarioId")
                        .IsUnique();

                    b.ToTable("usu_perfil", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuUsuario", b =>
                {
                    b.Property<long>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_id");

                    b.Property<int>("UsuCargoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_cargo_id");

                    b.Property<string>("UsuCpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_cpf");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_email");

                    b.Property<string>("UsuNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_nome");

                    b.Property<string>("UsuSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_senha");

                    b.Property<string>("UsuSobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_sobrenome");

                    b.Property<bool>("UsuStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usu_status");

                    b.Property<string>("UsuTelefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_telefone");

                    b.Property<DateTime?>("UsuUltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("usu_ultimo_login");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuCargoId");

                    b.HasIndex("UsuCpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usu_usuario_usu_cpf");

                    b.HasIndex("UsuEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_usu_usuario_usu_email");

                    b.HasIndex("UsuTelefone")
                        .IsUnique();

                    b.ToTable("usu_usuario", (string)null);
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaDocumento", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany("Documentos")
                        .HasForeignKey("IdaIdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ideia");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaIdeia", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaCategoria", "Categoria")
                        .WithMany("Ideias")
                        .HasForeignKey("IdaCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.IdaStatus", "Status")
                        .WithMany("Ideias")
                        .HasForeignKey("IdaStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("Ideias")
                        .HasForeignKey("IdaUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaInfo", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithOne("Info")
                        .HasForeignKey("TccSharkTank.Domain.Entities.IdaInfo", "IdaIdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ideia");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfNotificacao", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.NtfTipo", "Tipo")
                        .WithMany("Notificacoes")
                        .HasForeignKey("NtfTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("NotificacoesRecebidas")
                        .HasForeignKey("NtfUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpInfo", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.PrpAceite", "Aceite")
                        .WithMany("Infos")
                        .HasForeignKey("PrpAceiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.PrpProposta", "Proposta")
                        .WithMany("Infos")
                        .HasForeignKey("PrpPropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aceite");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpProposta", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany("Propostas")
                        .HasForeignKey("PrpIdeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("Propostas")
                        .HasForeignKey("PrpUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ideia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnLog", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.IdaIdeia", "Ideia")
                        .WithMany()
                        .HasForeignKey("TrnIdeiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TccSharkTank.Domain.Entities.PrpProposta", "Proposta")
                        .WithMany()
                        .HasForeignKey("TrnPropostaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TccSharkTank.Domain.Entities.TrnTipo", "Tipo")
                        .WithMany("Logs")
                        .HasForeignKey("TrnTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("TrnUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ideia");

                    b.Navigation("Proposta");

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuPerfil", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.UsuUsuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("TccSharkTank.Domain.Entities.UsuPerfil", "UsuUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuUsuario", b =>
                {
                    b.HasOne("TccSharkTank.Domain.Entities.UsuCargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("UsuCargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaCategoria", b =>
                {
                    b.Navigation("Ideias");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaIdeia", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Info");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.IdaStatus", b =>
                {
                    b.Navigation("Ideias");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.NtfTipo", b =>
                {
                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpAceite", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.PrpProposta", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.TrnTipo", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuCargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TccSharkTank.Domain.Entities.UsuUsuario", b =>
                {
                    b.Navigation("Ideias");

                    b.Navigation("Logs");

                    b.Navigation("NotificacoesRecebidas");

                    b.Navigation("Perfil");

                    b.Navigation("Propostas");
                });
#pragma warning restore 612, 618
        }
    }
}
